@api = https://staging.haciendola.dev/backend/test-front/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

### Obtener productos
GET {{api}}/products

### Producto
GET https://staging.haciendola.dev/backend/test-front/api/productOs/KNJS

### Iniciar sesión
POST {{api}}/users/login
Content-Type: application/json

{
  "user": "pepe",
  "password": "1234"
}

### Ordenes
GET {{api}}/users/getOrders
Authorization: Bearer {{token}}